### ISSUE TITLE
Create database in SQL

### ISSUE THREAD

**Issue by AbiHaddon** [Fr3dMer/softeng_module#20]
As a bioinformatics manager I want to have a safe and efficient repository of genetic test and panel information for use in the laboratory so that I can access it quickly and reliably

**Comment by AbiHaddon** [comment]
@AbiHaddon  and @Fr3dMer had a detailed discussion regarding structure of database 
- Initial DB structure provided by @AmyGrimwood 
![image](https://github.com/Fr3dMer/softeng_module/assets/128397378/36766d4c-f9b2-4ee9-ad9f-4b0cefcbc8df)
- New DB structure see below - removed patient table - felt that this information wasn't required and would allow for patients to be identified (need to maintain pseudonymisation). Updated panel table structure. 
![image](https://github.com/Fr3dMer/softeng_module/assets/128397378/4004cb8e-923c-4841-8ae1-912bfafb211b)

**Comment by AmyGrimwood** [comment]
I think either the JSON or the other gene info should be included, not both. The JSON will just include all the other gene info, so would have a lot of duplicate info

**Comment by Fr3dMer** [comment]
- Good point on repeating data, our thought was to take the most frequently required data and save in an already parsed and easy to access format, with the large JSON blob present, if more detailed info is required. But if the db is just a backup in-case the internet connection fails, we will normally be parsing a large JSON anyway straight from the API. Has this been over engineered and would the resources implementing this be better put elsewhere? @AmyGrimwood I'm leaning towards agreeing with you on the gene-detail column, however Ref seq's will need to be present as the JSON returned by the API returns them in embl format, while RefSeq was requested by users.

- In terms of the ref seqs, we should have been clearer, we were thinking of having them in a dict as {"HGNC_ID":"NC_00123.5",...}

- Additionally we were thinking of having the bed files saved next to the db in a folder, with the BED_file column holding the file path. This would meet two user requirements while also decreasing the size of the db. What's your thoughts @AmyGrimwood?

**Comment by AbiHaddon** [comment]
branch merged - new branch to be created for sprint 4
